Improve Containerfile
SUSE/technical-reference-documentation pull request #96
Opened 2023-08-21 14:02 UTC by dcermak

- fix `set -eux pipefail` to `set -euxo pipefail`, without the `o`, `pipefail` does nothing
- remove pointless `cd $NOTEBOOKS`
- define $NOTEBOOKS as a volume

2023-08-28 15:36 UTC, tlssuse requested changes
Good catch on `RUN set -eux**o** pipefail;`.
Let's make this change.

You are correct that changing to the $NOTEBOOKS directory (lines 558-559) are superfluous.
The guide uses a "launch script" to handle volume mapping when the container is run.
So, adding the VOLUME declaration to Containerfile is an unneeded complication.
I recommend deleting the directory change lines (558-559 of the original file) and NOT adding the `VOLUME $NOTEBOOKS` line.

Likewise, I agree that `cd $NOTEBOOKS; ` is unnecessary in the final `CMD` line.

2023-08-28 15:36 UTC, tlssuse commented on linux/start/jupyter/adoc/gs_sles_jupyter-jupyterlab_container.adoc
> +RUN set -euxo pipefail; \
Yes, this change should be made.

2023-08-28 15:36 UTC, tlssuse commented on linux/start/jupyter/adoc/gs_sles_jupyter-jupyterlab_container.adoc
> +VOLUME $NOTEBOOKS
The guide uses a "launch script" to handle volume mapping when the container is run.
Adding the VOLUME command to the Container file is an unnecessary complication.

The original lines 558 and 559 are irrelevant and can be removed.

2023-08-28 15:36 UTC, tlssuse commented on linux/start/jupyter/adoc/gs_sles_jupyter-jupyterlab_container.adoc
> +CMD jupyter-lab --ip=* --port=8888 --no-browser --notebook-dir=$NOTEBOOKS
`cd $NOTEBOOKS; ` is also irrelevant.
So, this suggested change should be accepted.

2023-08-29 15:09 UTC, chabowski commented
@tlssuse you are requesting one more change from @dcermak, correct? 
I will merge and push/publish the doc after this is done. Thanks!!

2023-09-11 11:17 UTC, chabowski commented
All requested changes have been implemented with PR #99. Closing this PR without merging.

2023-09-11 11:17 UTC, closed without merging